# Generated by Django 2.0.9 on 2019-03-02 11:13

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=255)),
                ('publish', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('mneed', 'Monthly Needs'), ('dneed', 'Daily Need'), ('want', 'Want')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('savingPer', models.IntegerField(validators=[django.core.validators.MinValueValidator(15)])),
                ('wantPer', models.IntegerField()),
                ('needPer', models.IntegerField()),
            ],
        ),
    ]
