# Generated by Django 2.0.9 on 2019-03-02 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='needPer',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(85)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='savingPer',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='money',
            name='wantPer',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(85)]),
        ),
    ]
