# Generated by Django 2.1.5 on 2019-03-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_famdetails_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='publish',
        ),
    ]
