# Generated by Django 2.0.9 on 2019-03-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20190302_2159'),
        ('person', '0003_auto_20190302_1932'),
    ]

    operations = [
    ]
