# Generated by Django 2.0.9 on 2019-03-02 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_merge_20190302_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='publish',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='salary',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='person.Famdetails'),
        ),
    ]
