# Generated by Django 2.0.9 on 2019-03-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20190302_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='salary',
        ),
    ]
